// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ElasticJob.proto

package com.choi.grpc;

public interface AddJobRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.choi.service.AddJobRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string param = 2;</code>
   * @return The param.
   */
  java.lang.String getParam();
  /**
   * <code>string param = 2;</code>
   * @return The bytes for param.
   */
  com.google.protobuf.ByteString
      getParamBytes();

  /**
   * <code>string scheduleType = 3;</code>
   * @return The scheduleType.
   */
  java.lang.String getScheduleType();
  /**
   * <code>string scheduleType = 3;</code>
   * @return The bytes for scheduleType.
   */
  com.google.protobuf.ByteString
      getScheduleTypeBytes();

  /**
   * <code>string scheduleParam = 4;</code>
   * @return The scheduleParam.
   */
  java.lang.String getScheduleParam();
  /**
   * <code>string scheduleParam = 4;</code>
   * @return The bytes for scheduleParam.
   */
  com.google.protobuf.ByteString
      getScheduleParamBytes();
}
