// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ElasticJob.proto

package com.choi.grpc;

/**
 * Protobuf type {@code com.choi.service.GrpcJobList}
 */
public final class GrpcJobList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.choi.service.GrpcJobList)
    GrpcJobListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GrpcJobList.newBuilder() to construct.
  private GrpcJobList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GrpcJobList() {
    grpcJobInfo_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GrpcJobList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.choi.grpc.grpcService.internal_static_com_choi_service_GrpcJobList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.choi.grpc.grpcService.internal_static_com_choi_service_GrpcJobList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.choi.grpc.GrpcJobList.class, com.choi.grpc.GrpcJobList.Builder.class);
  }

  public static final int GRPCJOBINFO_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.choi.grpc.GrpcJobInfo> grpcJobInfo_;
  /**
   * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.choi.grpc.GrpcJobInfo> getGrpcJobInfoList() {
    return grpcJobInfo_;
  }
  /**
   * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.choi.grpc.GrpcJobInfoOrBuilder> 
      getGrpcJobInfoOrBuilderList() {
    return grpcJobInfo_;
  }
  /**
   * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
   */
  @java.lang.Override
  public int getGrpcJobInfoCount() {
    return grpcJobInfo_.size();
  }
  /**
   * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
   */
  @java.lang.Override
  public com.choi.grpc.GrpcJobInfo getGrpcJobInfo(int index) {
    return grpcJobInfo_.get(index);
  }
  /**
   * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
   */
  @java.lang.Override
  public com.choi.grpc.GrpcJobInfoOrBuilder getGrpcJobInfoOrBuilder(
      int index) {
    return grpcJobInfo_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < grpcJobInfo_.size(); i++) {
      output.writeMessage(1, grpcJobInfo_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < grpcJobInfo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, grpcJobInfo_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.choi.grpc.GrpcJobList)) {
      return super.equals(obj);
    }
    com.choi.grpc.GrpcJobList other = (com.choi.grpc.GrpcJobList) obj;

    if (!getGrpcJobInfoList()
        .equals(other.getGrpcJobInfoList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getGrpcJobInfoCount() > 0) {
      hash = (37 * hash) + GRPCJOBINFO_FIELD_NUMBER;
      hash = (53 * hash) + getGrpcJobInfoList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.choi.grpc.GrpcJobList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.choi.grpc.GrpcJobList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.choi.grpc.GrpcJobList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.choi.grpc.GrpcJobList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.choi.grpc.GrpcJobList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.choi.grpc.GrpcJobList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.choi.grpc.GrpcJobList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.choi.grpc.GrpcJobList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.choi.grpc.GrpcJobList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.choi.grpc.GrpcJobList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.choi.grpc.GrpcJobList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.choi.grpc.GrpcJobList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.choi.grpc.GrpcJobList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.choi.service.GrpcJobList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.choi.service.GrpcJobList)
      com.choi.grpc.GrpcJobListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.choi.grpc.grpcService.internal_static_com_choi_service_GrpcJobList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.choi.grpc.grpcService.internal_static_com_choi_service_GrpcJobList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.choi.grpc.GrpcJobList.class, com.choi.grpc.GrpcJobList.Builder.class);
    }

    // Construct using com.choi.grpc.GrpcJobList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (grpcJobInfoBuilder_ == null) {
        grpcJobInfo_ = java.util.Collections.emptyList();
      } else {
        grpcJobInfo_ = null;
        grpcJobInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.choi.grpc.grpcService.internal_static_com_choi_service_GrpcJobList_descriptor;
    }

    @java.lang.Override
    public com.choi.grpc.GrpcJobList getDefaultInstanceForType() {
      return com.choi.grpc.GrpcJobList.getDefaultInstance();
    }

    @java.lang.Override
    public com.choi.grpc.GrpcJobList build() {
      com.choi.grpc.GrpcJobList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.choi.grpc.GrpcJobList buildPartial() {
      com.choi.grpc.GrpcJobList result = new com.choi.grpc.GrpcJobList(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.choi.grpc.GrpcJobList result) {
      if (grpcJobInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          grpcJobInfo_ = java.util.Collections.unmodifiableList(grpcJobInfo_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.grpcJobInfo_ = grpcJobInfo_;
      } else {
        result.grpcJobInfo_ = grpcJobInfoBuilder_.build();
      }
    }

    private void buildPartial0(com.choi.grpc.GrpcJobList result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.choi.grpc.GrpcJobList) {
        return mergeFrom((com.choi.grpc.GrpcJobList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.choi.grpc.GrpcJobList other) {
      if (other == com.choi.grpc.GrpcJobList.getDefaultInstance()) return this;
      if (grpcJobInfoBuilder_ == null) {
        if (!other.grpcJobInfo_.isEmpty()) {
          if (grpcJobInfo_.isEmpty()) {
            grpcJobInfo_ = other.grpcJobInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureGrpcJobInfoIsMutable();
            grpcJobInfo_.addAll(other.grpcJobInfo_);
          }
          onChanged();
        }
      } else {
        if (!other.grpcJobInfo_.isEmpty()) {
          if (grpcJobInfoBuilder_.isEmpty()) {
            grpcJobInfoBuilder_.dispose();
            grpcJobInfoBuilder_ = null;
            grpcJobInfo_ = other.grpcJobInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
            grpcJobInfoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getGrpcJobInfoFieldBuilder() : null;
          } else {
            grpcJobInfoBuilder_.addAllMessages(other.grpcJobInfo_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.choi.grpc.GrpcJobInfo m =
                  input.readMessage(
                      com.choi.grpc.GrpcJobInfo.parser(),
                      extensionRegistry);
              if (grpcJobInfoBuilder_ == null) {
                ensureGrpcJobInfoIsMutable();
                grpcJobInfo_.add(m);
              } else {
                grpcJobInfoBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.choi.grpc.GrpcJobInfo> grpcJobInfo_ =
      java.util.Collections.emptyList();
    private void ensureGrpcJobInfoIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        grpcJobInfo_ = new java.util.ArrayList<com.choi.grpc.GrpcJobInfo>(grpcJobInfo_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.choi.grpc.GrpcJobInfo, com.choi.grpc.GrpcJobInfo.Builder, com.choi.grpc.GrpcJobInfoOrBuilder> grpcJobInfoBuilder_;

    /**
     * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
     */
    public java.util.List<com.choi.grpc.GrpcJobInfo> getGrpcJobInfoList() {
      if (grpcJobInfoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(grpcJobInfo_);
      } else {
        return grpcJobInfoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
     */
    public int getGrpcJobInfoCount() {
      if (grpcJobInfoBuilder_ == null) {
        return grpcJobInfo_.size();
      } else {
        return grpcJobInfoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
     */
    public com.choi.grpc.GrpcJobInfo getGrpcJobInfo(int index) {
      if (grpcJobInfoBuilder_ == null) {
        return grpcJobInfo_.get(index);
      } else {
        return grpcJobInfoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
     */
    public Builder setGrpcJobInfo(
        int index, com.choi.grpc.GrpcJobInfo value) {
      if (grpcJobInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGrpcJobInfoIsMutable();
        grpcJobInfo_.set(index, value);
        onChanged();
      } else {
        grpcJobInfoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
     */
    public Builder setGrpcJobInfo(
        int index, com.choi.grpc.GrpcJobInfo.Builder builderForValue) {
      if (grpcJobInfoBuilder_ == null) {
        ensureGrpcJobInfoIsMutable();
        grpcJobInfo_.set(index, builderForValue.build());
        onChanged();
      } else {
        grpcJobInfoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
     */
    public Builder addGrpcJobInfo(com.choi.grpc.GrpcJobInfo value) {
      if (grpcJobInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGrpcJobInfoIsMutable();
        grpcJobInfo_.add(value);
        onChanged();
      } else {
        grpcJobInfoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
     */
    public Builder addGrpcJobInfo(
        int index, com.choi.grpc.GrpcJobInfo value) {
      if (grpcJobInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGrpcJobInfoIsMutable();
        grpcJobInfo_.add(index, value);
        onChanged();
      } else {
        grpcJobInfoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
     */
    public Builder addGrpcJobInfo(
        com.choi.grpc.GrpcJobInfo.Builder builderForValue) {
      if (grpcJobInfoBuilder_ == null) {
        ensureGrpcJobInfoIsMutable();
        grpcJobInfo_.add(builderForValue.build());
        onChanged();
      } else {
        grpcJobInfoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
     */
    public Builder addGrpcJobInfo(
        int index, com.choi.grpc.GrpcJobInfo.Builder builderForValue) {
      if (grpcJobInfoBuilder_ == null) {
        ensureGrpcJobInfoIsMutable();
        grpcJobInfo_.add(index, builderForValue.build());
        onChanged();
      } else {
        grpcJobInfoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
     */
    public Builder addAllGrpcJobInfo(
        java.lang.Iterable<? extends com.choi.grpc.GrpcJobInfo> values) {
      if (grpcJobInfoBuilder_ == null) {
        ensureGrpcJobInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, grpcJobInfo_);
        onChanged();
      } else {
        grpcJobInfoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
     */
    public Builder clearGrpcJobInfo() {
      if (grpcJobInfoBuilder_ == null) {
        grpcJobInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        grpcJobInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
     */
    public Builder removeGrpcJobInfo(int index) {
      if (grpcJobInfoBuilder_ == null) {
        ensureGrpcJobInfoIsMutable();
        grpcJobInfo_.remove(index);
        onChanged();
      } else {
        grpcJobInfoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
     */
    public com.choi.grpc.GrpcJobInfo.Builder getGrpcJobInfoBuilder(
        int index) {
      return getGrpcJobInfoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
     */
    public com.choi.grpc.GrpcJobInfoOrBuilder getGrpcJobInfoOrBuilder(
        int index) {
      if (grpcJobInfoBuilder_ == null) {
        return grpcJobInfo_.get(index);  } else {
        return grpcJobInfoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
     */
    public java.util.List<? extends com.choi.grpc.GrpcJobInfoOrBuilder> 
         getGrpcJobInfoOrBuilderList() {
      if (grpcJobInfoBuilder_ != null) {
        return grpcJobInfoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(grpcJobInfo_);
      }
    }
    /**
     * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
     */
    public com.choi.grpc.GrpcJobInfo.Builder addGrpcJobInfoBuilder() {
      return getGrpcJobInfoFieldBuilder().addBuilder(
          com.choi.grpc.GrpcJobInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
     */
    public com.choi.grpc.GrpcJobInfo.Builder addGrpcJobInfoBuilder(
        int index) {
      return getGrpcJobInfoFieldBuilder().addBuilder(
          index, com.choi.grpc.GrpcJobInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
     */
    public java.util.List<com.choi.grpc.GrpcJobInfo.Builder> 
         getGrpcJobInfoBuilderList() {
      return getGrpcJobInfoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.choi.grpc.GrpcJobInfo, com.choi.grpc.GrpcJobInfo.Builder, com.choi.grpc.GrpcJobInfoOrBuilder> 
        getGrpcJobInfoFieldBuilder() {
      if (grpcJobInfoBuilder_ == null) {
        grpcJobInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.choi.grpc.GrpcJobInfo, com.choi.grpc.GrpcJobInfo.Builder, com.choi.grpc.GrpcJobInfoOrBuilder>(
                grpcJobInfo_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        grpcJobInfo_ = null;
      }
      return grpcJobInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.choi.service.GrpcJobList)
  }

  // @@protoc_insertion_point(class_scope:com.choi.service.GrpcJobList)
  private static final com.choi.grpc.GrpcJobList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.choi.grpc.GrpcJobList();
  }

  public static com.choi.grpc.GrpcJobList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GrpcJobList>
      PARSER = new com.google.protobuf.AbstractParser<GrpcJobList>() {
    @java.lang.Override
    public GrpcJobList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GrpcJobList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GrpcJobList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.choi.grpc.GrpcJobList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

