// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ElasticJob.proto

package com.choi.grpc;

public interface GrpcJobInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.choi.service.GrpcJobInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string param = 3;</code>
   * @return The param.
   */
  java.lang.String getParam();
  /**
   * <code>string param = 3;</code>
   * @return The bytes for param.
   */
  com.google.protobuf.ByteString
      getParamBytes();
}
