// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ElasticJob.proto

package com.choi.grpc;

public interface GrpcJobListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.choi.service.GrpcJobList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
   */
  java.util.List<com.choi.grpc.GrpcJobInfo> 
      getGrpcJobInfoList();
  /**
   * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
   */
  com.choi.grpc.GrpcJobInfo getGrpcJobInfo(int index);
  /**
   * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
   */
  int getGrpcJobInfoCount();
  /**
   * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
   */
  java.util.List<? extends com.choi.grpc.GrpcJobInfoOrBuilder> 
      getGrpcJobInfoOrBuilderList();
  /**
   * <code>repeated .com.choi.service.GrpcJobInfo grpcJobInfo = 1;</code>
   */
  com.choi.grpc.GrpcJobInfoOrBuilder getGrpcJobInfoOrBuilder(
      int index);
}
