// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ElasticJob.proto

package com.choi.grpc;

public final class grpcService {
  private grpcService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_choi_service_RegisterNodeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_choi_service_RegisterNodeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_choi_service_RegisterNodeReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_choi_service_RegisterNodeReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_choi_service_JobInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_choi_service_JobInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_choi_service_JobRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_choi_service_JobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_choi_service_JobReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_choi_service_JobReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_choi_service_JobList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_choi_service_JobList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_choi_service_DeregisterNodeReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_choi_service_DeregisterNodeReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_choi_service_DeregisterNodeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_choi_service_DeregisterNodeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_choi_service_AddJobInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_choi_service_AddJobInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_choi_service_AddJobReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_choi_service_AddJobReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_choi_service_ErrorCode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_choi_service_ErrorCode_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020ElasticJob.proto\022\020com.choi.service\"M\n\023" +
      "RegisterNodeRequest\022\016\n\006nodeId\030\001 \001(\t\022\021\n\tr" +
      "esources\030\002 \001(\t\022\023\n\013maxParallel\030\003 \001(\t\"=\n\021R" +
      "egisterNodeReply\022(\n\003err\030\001 \001(\0132\033.com.choi" +
      ".service.ErrorCode\"2\n\007JobInfo\022\n\n\002id\030\001 \001(" +
      "\t\022\014\n\004name\030\002 \001(\t\022\r\n\005param\030\003 \001(\t\"F\n\nJobReq" +
      "uest\022\016\n\006nodeId\030\001 \001(\t\022\020\n\010resource\030\002 \001(\t\022\026" +
      "\n\016parallelJobNum\030\003 \001(\t\"`\n\010JobReply\022*\n\007jo" +
      "bList\030\001 \001(\0132\031.com.choi.service.JobList\022(" +
      "\n\003err\030\002 \001(\0132\033.com.choi.service.ErrorCode" +
      "\"5\n\007JobList\022*\n\007jobInfo\030\001 \003(\0132\031.com.choi." +
      "service.JobInfo\"?\n\023DeregisterNodeReply\022(" +
      "\n\003err\030\001 \001(\0132\033.com.choi.service.ErrorCode" +
      "\"\'\n\025DeregisterNodeRequest\022\016\n\006nodeId\030\001 \001(" +
      "\t\"V\n\nAddJobInfo\022\014\n\004name\030\001 \001(\t\022\r\n\005param\030\002" +
      " \001(\t\022\024\n\014scheduleType\030\003 \001(\t\022\025\n\rschedulePa" +
      "ram\030\004 \001(\t\"7\n\013AddJobReply\022(\n\003err\030\001 \001(\0132\033." +
      "com.choi.service.ErrorCode\"*\n\tErrorCode\022" +
      "\014\n\004code\030\001 \001(\t\022\017\n\007message\030\002 \001(\t2\344\002\n\021Elast" +
      "icJobService\022\\\n\014RegisterNode\022%.com.choi." +
      "service.RegisterNodeRequest\032#.com.choi.s" +
      "ervice.RegisterNodeReply\"\000\022b\n\016Deregister" +
      "Node\022\'.com.choi.service.DeregisterNodeRe" +
      "quest\032%.com.choi.service.DeregisterNodeR" +
      "eply\"\000\022D\n\006GetJob\022\034.com.choi.service.JobR" +
      "equest\032\032.com.choi.service.JobReply\"\000\022G\n\006" +
      "AddJob\022\034.com.choi.service.AddJobInfo\032\035.c" +
      "om.choi.service.AddJobReply\"\000B\036\n\rcom.cho" +
      "i.grpcB\013grpcServiceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_choi_service_RegisterNodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_choi_service_RegisterNodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_choi_service_RegisterNodeRequest_descriptor,
        new String[] { "NodeId", "Resources", "MaxParallel", });
    internal_static_com_choi_service_RegisterNodeReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_choi_service_RegisterNodeReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_choi_service_RegisterNodeReply_descriptor,
        new String[] { "Err", });
    internal_static_com_choi_service_JobInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_choi_service_JobInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_choi_service_JobInfo_descriptor,
        new String[] { "Id", "Name", "Param", });
    internal_static_com_choi_service_JobRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_choi_service_JobRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_choi_service_JobRequest_descriptor,
        new String[] { "NodeId", "Resource", "ParallelJobNum", });
    internal_static_com_choi_service_JobReply_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_choi_service_JobReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_choi_service_JobReply_descriptor,
        new String[] { "JobList", "Err", });
    internal_static_com_choi_service_JobList_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_choi_service_JobList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_choi_service_JobList_descriptor,
        new String[] { "JobInfo", });
    internal_static_com_choi_service_DeregisterNodeReply_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_choi_service_DeregisterNodeReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_choi_service_DeregisterNodeReply_descriptor,
        new String[] { "Err", });
    internal_static_com_choi_service_DeregisterNodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_choi_service_DeregisterNodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_choi_service_DeregisterNodeRequest_descriptor,
        new String[] { "NodeId", });
    internal_static_com_choi_service_AddJobInfo_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_choi_service_AddJobInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_choi_service_AddJobInfo_descriptor,
        new String[] { "Name", "Param", "ScheduleType", "ScheduleParam", });
    internal_static_com_choi_service_AddJobReply_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_choi_service_AddJobReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_choi_service_AddJobReply_descriptor,
        new String[] { "Err", });
    internal_static_com_choi_service_ErrorCode_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_choi_service_ErrorCode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_choi_service_ErrorCode_descriptor,
        new String[] { "Code", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
