// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ElasticJob.proto

package com.choi.grpc;

import java.util.List;

/**
 * Protobuf type {@code com.choi.service.JobList}
 */
public final class JobList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.choi.service.JobList)
    JobListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JobList.newBuilder() to construct.
  private JobList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JobList() {
    jobInfo_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new JobList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpcService.internal_static_com_choi_service_JobList_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpcService.internal_static_com_choi_service_JobList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            JobList.class, Builder.class);
  }

  public static final int JOBINFO_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private List<JobInfo> jobInfo_;
  /**
   * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
   */
  @Override
  public List<JobInfo> getJobInfoList() {
    return jobInfo_;
  }
  /**
   * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
   */
  @Override
  public List<? extends JobInfoOrBuilder>
      getJobInfoOrBuilderList() {
    return jobInfo_;
  }
  /**
   * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
   */
  @Override
  public int getJobInfoCount() {
    return jobInfo_.size();
  }
  /**
   * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
   */
  @Override
  public JobInfo getJobInfo(int index) {
    return jobInfo_.get(index);
  }
  /**
   * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
   */
  @Override
  public JobInfoOrBuilder getJobInfoOrBuilder(
      int index) {
    return jobInfo_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < jobInfo_.size(); i++) {
      output.writeMessage(1, jobInfo_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < jobInfo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, jobInfo_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof JobList)) {
      return super.equals(obj);
    }
    JobList other = (JobList) obj;

    if (!getJobInfoList()
        .equals(other.getJobInfoList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getJobInfoCount() > 0) {
      hash = (37 * hash) + JOBINFO_FIELD_NUMBER;
      hash = (53 * hash) + getJobInfoList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static JobList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static JobList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static JobList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static JobList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static JobList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static JobList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static JobList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static JobList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static JobList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static JobList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static JobList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static JobList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(JobList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.choi.service.JobList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.choi.service.JobList)
      JobListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpcService.internal_static_com_choi_service_JobList_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpcService.internal_static_com_choi_service_JobList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              JobList.class, Builder.class);
    }

    // Construct using com.choi.grpc.JobList.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (jobInfoBuilder_ == null) {
        jobInfo_ = java.util.Collections.emptyList();
      } else {
        jobInfo_ = null;
        jobInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpcService.internal_static_com_choi_service_JobList_descriptor;
    }

    @Override
    public JobList getDefaultInstanceForType() {
      return JobList.getDefaultInstance();
    }

    @Override
    public JobList build() {
      JobList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public JobList buildPartial() {
      JobList result = new JobList(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(JobList result) {
      if (jobInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          jobInfo_ = java.util.Collections.unmodifiableList(jobInfo_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.jobInfo_ = jobInfo_;
      } else {
        result.jobInfo_ = jobInfoBuilder_.build();
      }
    }

    private void buildPartial0(JobList result) {
      int from_bitField0_ = bitField0_;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof JobList) {
        return mergeFrom((JobList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(JobList other) {
      if (other == JobList.getDefaultInstance()) return this;
      if (jobInfoBuilder_ == null) {
        if (!other.jobInfo_.isEmpty()) {
          if (jobInfo_.isEmpty()) {
            jobInfo_ = other.jobInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureJobInfoIsMutable();
            jobInfo_.addAll(other.jobInfo_);
          }
          onChanged();
        }
      } else {
        if (!other.jobInfo_.isEmpty()) {
          if (jobInfoBuilder_.isEmpty()) {
            jobInfoBuilder_.dispose();
            jobInfoBuilder_ = null;
            jobInfo_ = other.jobInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
            jobInfoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getJobInfoFieldBuilder() : null;
          } else {
            jobInfoBuilder_.addAllMessages(other.jobInfo_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              JobInfo m =
                  input.readMessage(
                      JobInfo.parser(),
                      extensionRegistry);
              if (jobInfoBuilder_ == null) {
                ensureJobInfoIsMutable();
                jobInfo_.add(m);
              } else {
                jobInfoBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private List<JobInfo> jobInfo_ =
      java.util.Collections.emptyList();
    private void ensureJobInfoIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        jobInfo_ = new java.util.ArrayList<JobInfo>(jobInfo_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        JobInfo, JobInfo.Builder, JobInfoOrBuilder> jobInfoBuilder_;

    /**
     * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
     */
    public List<JobInfo> getJobInfoList() {
      if (jobInfoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(jobInfo_);
      } else {
        return jobInfoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
     */
    public int getJobInfoCount() {
      if (jobInfoBuilder_ == null) {
        return jobInfo_.size();
      } else {
        return jobInfoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
     */
    public JobInfo getJobInfo(int index) {
      if (jobInfoBuilder_ == null) {
        return jobInfo_.get(index);
      } else {
        return jobInfoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
     */
    public Builder setJobInfo(
        int index, JobInfo value) {
      if (jobInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobInfoIsMutable();
        jobInfo_.set(index, value);
        onChanged();
      } else {
        jobInfoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
     */
    public Builder setJobInfo(
        int index, JobInfo.Builder builderForValue) {
      if (jobInfoBuilder_ == null) {
        ensureJobInfoIsMutable();
        jobInfo_.set(index, builderForValue.build());
        onChanged();
      } else {
        jobInfoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
     */
    public Builder addJobInfo(JobInfo value) {
      if (jobInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobInfoIsMutable();
        jobInfo_.add(value);
        onChanged();
      } else {
        jobInfoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
     */
    public Builder addJobInfo(
        int index, JobInfo value) {
      if (jobInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureJobInfoIsMutable();
        jobInfo_.add(index, value);
        onChanged();
      } else {
        jobInfoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
     */
    public Builder addJobInfo(
        JobInfo.Builder builderForValue) {
      if (jobInfoBuilder_ == null) {
        ensureJobInfoIsMutable();
        jobInfo_.add(builderForValue.build());
        onChanged();
      } else {
        jobInfoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
     */
    public Builder addJobInfo(
        int index, JobInfo.Builder builderForValue) {
      if (jobInfoBuilder_ == null) {
        ensureJobInfoIsMutable();
        jobInfo_.add(index, builderForValue.build());
        onChanged();
      } else {
        jobInfoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
     */
    public Builder addAllJobInfo(
            List<com.choi.pojo.JobInfo> values) {
      if (jobInfoBuilder_ == null) {
        ensureJobInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, jobInfo_);
        onChanged();
      } else {
        jobInfoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
     */
    public Builder clearJobInfo() {
      if (jobInfoBuilder_ == null) {
        jobInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        jobInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
     */
    public Builder removeJobInfo(int index) {
      if (jobInfoBuilder_ == null) {
        ensureJobInfoIsMutable();
        jobInfo_.remove(index);
        onChanged();
      } else {
        jobInfoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
     */
    public JobInfo.Builder getJobInfoBuilder(
        int index) {
      return getJobInfoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
     */
    public JobInfoOrBuilder getJobInfoOrBuilder(
        int index) {
      if (jobInfoBuilder_ == null) {
        return jobInfo_.get(index);  } else {
        return jobInfoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
     */
    public List<? extends JobInfoOrBuilder>
         getJobInfoOrBuilderList() {
      if (jobInfoBuilder_ != null) {
        return jobInfoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(jobInfo_);
      }
    }
    /**
     * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
     */
    public JobInfo.Builder addJobInfoBuilder() {
      return getJobInfoFieldBuilder().addBuilder(
          JobInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
     */
    public JobInfo.Builder addJobInfoBuilder(
        int index) {
      return getJobInfoFieldBuilder().addBuilder(
          index, JobInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
     */
    public List<JobInfo.Builder>
         getJobInfoBuilderList() {
      return getJobInfoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        JobInfo, JobInfo.Builder, JobInfoOrBuilder>
        getJobInfoFieldBuilder() {
      if (jobInfoBuilder_ == null) {
        jobInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            JobInfo, JobInfo.Builder, JobInfoOrBuilder>(
                jobInfo_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        jobInfo_ = null;
      }
      return jobInfoBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.choi.service.JobList)
  }

  // @@protoc_insertion_point(class_scope:com.choi.service.JobList)
  private static final JobList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new JobList();
  }

  public static JobList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JobList>
      PARSER = new com.google.protobuf.AbstractParser<JobList>() {
    @Override
    public JobList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<JobList> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<JobList> getParserForType() {
    return PARSER;
  }

  @Override
  public JobList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

