// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ElasticJob.proto

package com.choi.grpc;

public interface JobListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.choi.service.JobList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
   */
  java.util.List<JobInfo>
      getJobInfoList();
  /**
   * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
   */
  JobInfo getJobInfo(int index);
  /**
   * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
   */
  int getJobInfoCount();
  /**
   * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
   */
  java.util.List<? extends JobInfoOrBuilder>
      getJobInfoOrBuilderList();
  /**
   * <code>repeated .com.choi.service.JobInfo jobInfo = 1;</code>
   */
  JobInfoOrBuilder getJobInfoOrBuilder(
      int index);
}
