// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ElasticJob.proto

package com.choi.grpc;

/**
 * Protobuf type {@code com.choi.service.JobReply}
 */
public final class JobReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.choi.service.JobReply)
    JobReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JobReply.newBuilder() to construct.
  private JobReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JobReply() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new JobReply();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.choi.grpc.grpcService.internal_static_com_choi_service_JobReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.choi.grpc.grpcService.internal_static_com_choi_service_JobReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.choi.grpc.JobReply.class, com.choi.grpc.JobReply.Builder.class);
  }

  private int bitField0_;
  public static final int GRPCJOBLIST_FIELD_NUMBER = 1;
  private com.choi.grpc.GrpcJobList grpcJobList_;
  /**
   * <code>.com.choi.service.GrpcJobList grpcJobList = 1;</code>
   * @return Whether the grpcJobList field is set.
   */
  @java.lang.Override
  public boolean hasGrpcJobList() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.choi.service.GrpcJobList grpcJobList = 1;</code>
   * @return The grpcJobList.
   */
  @java.lang.Override
  public com.choi.grpc.GrpcJobList getGrpcJobList() {
    return grpcJobList_ == null ? com.choi.grpc.GrpcJobList.getDefaultInstance() : grpcJobList_;
  }
  /**
   * <code>.com.choi.service.GrpcJobList grpcJobList = 1;</code>
   */
  @java.lang.Override
  public com.choi.grpc.GrpcJobListOrBuilder getGrpcJobListOrBuilder() {
    return grpcJobList_ == null ? com.choi.grpc.GrpcJobList.getDefaultInstance() : grpcJobList_;
  }

  public static final int ERR_FIELD_NUMBER = 2;
  private com.choi.grpc.ErrorCode err_;
  /**
   * <code>.com.choi.service.ErrorCode err = 2;</code>
   * @return Whether the err field is set.
   */
  @java.lang.Override
  public boolean hasErr() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.com.choi.service.ErrorCode err = 2;</code>
   * @return The err.
   */
  @java.lang.Override
  public com.choi.grpc.ErrorCode getErr() {
    return err_ == null ? com.choi.grpc.ErrorCode.getDefaultInstance() : err_;
  }
  /**
   * <code>.com.choi.service.ErrorCode err = 2;</code>
   */
  @java.lang.Override
  public com.choi.grpc.ErrorCodeOrBuilder getErrOrBuilder() {
    return err_ == null ? com.choi.grpc.ErrorCode.getDefaultInstance() : err_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getGrpcJobList());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getErr());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getGrpcJobList());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getErr());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.choi.grpc.JobReply)) {
      return super.equals(obj);
    }
    com.choi.grpc.JobReply other = (com.choi.grpc.JobReply) obj;

    if (hasGrpcJobList() != other.hasGrpcJobList()) return false;
    if (hasGrpcJobList()) {
      if (!getGrpcJobList()
          .equals(other.getGrpcJobList())) return false;
    }
    if (hasErr() != other.hasErr()) return false;
    if (hasErr()) {
      if (!getErr()
          .equals(other.getErr())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasGrpcJobList()) {
      hash = (37 * hash) + GRPCJOBLIST_FIELD_NUMBER;
      hash = (53 * hash) + getGrpcJobList().hashCode();
    }
    if (hasErr()) {
      hash = (37 * hash) + ERR_FIELD_NUMBER;
      hash = (53 * hash) + getErr().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.choi.grpc.JobReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.choi.grpc.JobReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.choi.grpc.JobReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.choi.grpc.JobReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.choi.grpc.JobReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.choi.grpc.JobReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.choi.grpc.JobReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.choi.grpc.JobReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.choi.grpc.JobReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.choi.grpc.JobReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.choi.grpc.JobReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.choi.grpc.JobReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.choi.grpc.JobReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.choi.service.JobReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.choi.service.JobReply)
      com.choi.grpc.JobReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.choi.grpc.grpcService.internal_static_com_choi_service_JobReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.choi.grpc.grpcService.internal_static_com_choi_service_JobReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.choi.grpc.JobReply.class, com.choi.grpc.JobReply.Builder.class);
    }

    // Construct using com.choi.grpc.JobReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getGrpcJobListFieldBuilder();
        getErrFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      grpcJobList_ = null;
      if (grpcJobListBuilder_ != null) {
        grpcJobListBuilder_.dispose();
        grpcJobListBuilder_ = null;
      }
      err_ = null;
      if (errBuilder_ != null) {
        errBuilder_.dispose();
        errBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.choi.grpc.grpcService.internal_static_com_choi_service_JobReply_descriptor;
    }

    @java.lang.Override
    public com.choi.grpc.JobReply getDefaultInstanceForType() {
      return com.choi.grpc.JobReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.choi.grpc.JobReply build() {
      com.choi.grpc.JobReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.choi.grpc.JobReply buildPartial() {
      com.choi.grpc.JobReply result = new com.choi.grpc.JobReply(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.choi.grpc.JobReply result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.grpcJobList_ = grpcJobListBuilder_ == null
            ? grpcJobList_
            : grpcJobListBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.err_ = errBuilder_ == null
            ? err_
            : errBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.choi.grpc.JobReply) {
        return mergeFrom((com.choi.grpc.JobReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.choi.grpc.JobReply other) {
      if (other == com.choi.grpc.JobReply.getDefaultInstance()) return this;
      if (other.hasGrpcJobList()) {
        mergeGrpcJobList(other.getGrpcJobList());
      }
      if (other.hasErr()) {
        mergeErr(other.getErr());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getGrpcJobListFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getErrFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.choi.grpc.GrpcJobList grpcJobList_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.choi.grpc.GrpcJobList, com.choi.grpc.GrpcJobList.Builder, com.choi.grpc.GrpcJobListOrBuilder> grpcJobListBuilder_;
    /**
     * <code>.com.choi.service.GrpcJobList grpcJobList = 1;</code>
     * @return Whether the grpcJobList field is set.
     */
    public boolean hasGrpcJobList() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.choi.service.GrpcJobList grpcJobList = 1;</code>
     * @return The grpcJobList.
     */
    public com.choi.grpc.GrpcJobList getGrpcJobList() {
      if (grpcJobListBuilder_ == null) {
        return grpcJobList_ == null ? com.choi.grpc.GrpcJobList.getDefaultInstance() : grpcJobList_;
      } else {
        return grpcJobListBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.choi.service.GrpcJobList grpcJobList = 1;</code>
     */
    public Builder setGrpcJobList(com.choi.grpc.GrpcJobList value) {
      if (grpcJobListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        grpcJobList_ = value;
      } else {
        grpcJobListBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.choi.service.GrpcJobList grpcJobList = 1;</code>
     */
    public Builder setGrpcJobList(
        com.choi.grpc.GrpcJobList.Builder builderForValue) {
      if (grpcJobListBuilder_ == null) {
        grpcJobList_ = builderForValue.build();
      } else {
        grpcJobListBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.choi.service.GrpcJobList grpcJobList = 1;</code>
     */
    public Builder mergeGrpcJobList(com.choi.grpc.GrpcJobList value) {
      if (grpcJobListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          grpcJobList_ != null &&
          grpcJobList_ != com.choi.grpc.GrpcJobList.getDefaultInstance()) {
          getGrpcJobListBuilder().mergeFrom(value);
        } else {
          grpcJobList_ = value;
        }
      } else {
        grpcJobListBuilder_.mergeFrom(value);
      }
      if (grpcJobList_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.choi.service.GrpcJobList grpcJobList = 1;</code>
     */
    public Builder clearGrpcJobList() {
      bitField0_ = (bitField0_ & ~0x00000001);
      grpcJobList_ = null;
      if (grpcJobListBuilder_ != null) {
        grpcJobListBuilder_.dispose();
        grpcJobListBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.choi.service.GrpcJobList grpcJobList = 1;</code>
     */
    public com.choi.grpc.GrpcJobList.Builder getGrpcJobListBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getGrpcJobListFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.choi.service.GrpcJobList grpcJobList = 1;</code>
     */
    public com.choi.grpc.GrpcJobListOrBuilder getGrpcJobListOrBuilder() {
      if (grpcJobListBuilder_ != null) {
        return grpcJobListBuilder_.getMessageOrBuilder();
      } else {
        return grpcJobList_ == null ?
            com.choi.grpc.GrpcJobList.getDefaultInstance() : grpcJobList_;
      }
    }
    /**
     * <code>.com.choi.service.GrpcJobList grpcJobList = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.choi.grpc.GrpcJobList, com.choi.grpc.GrpcJobList.Builder, com.choi.grpc.GrpcJobListOrBuilder> 
        getGrpcJobListFieldBuilder() {
      if (grpcJobListBuilder_ == null) {
        grpcJobListBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.choi.grpc.GrpcJobList, com.choi.grpc.GrpcJobList.Builder, com.choi.grpc.GrpcJobListOrBuilder>(
                getGrpcJobList(),
                getParentForChildren(),
                isClean());
        grpcJobList_ = null;
      }
      return grpcJobListBuilder_;
    }

    private com.choi.grpc.ErrorCode err_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.choi.grpc.ErrorCode, com.choi.grpc.ErrorCode.Builder, com.choi.grpc.ErrorCodeOrBuilder> errBuilder_;
    /**
     * <code>.com.choi.service.ErrorCode err = 2;</code>
     * @return Whether the err field is set.
     */
    public boolean hasErr() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.com.choi.service.ErrorCode err = 2;</code>
     * @return The err.
     */
    public com.choi.grpc.ErrorCode getErr() {
      if (errBuilder_ == null) {
        return err_ == null ? com.choi.grpc.ErrorCode.getDefaultInstance() : err_;
      } else {
        return errBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.choi.service.ErrorCode err = 2;</code>
     */
    public Builder setErr(com.choi.grpc.ErrorCode value) {
      if (errBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        err_ = value;
      } else {
        errBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.choi.service.ErrorCode err = 2;</code>
     */
    public Builder setErr(
        com.choi.grpc.ErrorCode.Builder builderForValue) {
      if (errBuilder_ == null) {
        err_ = builderForValue.build();
      } else {
        errBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.com.choi.service.ErrorCode err = 2;</code>
     */
    public Builder mergeErr(com.choi.grpc.ErrorCode value) {
      if (errBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          err_ != null &&
          err_ != com.choi.grpc.ErrorCode.getDefaultInstance()) {
          getErrBuilder().mergeFrom(value);
        } else {
          err_ = value;
        }
      } else {
        errBuilder_.mergeFrom(value);
      }
      if (err_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.choi.service.ErrorCode err = 2;</code>
     */
    public Builder clearErr() {
      bitField0_ = (bitField0_ & ~0x00000002);
      err_ = null;
      if (errBuilder_ != null) {
        errBuilder_.dispose();
        errBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.choi.service.ErrorCode err = 2;</code>
     */
    public com.choi.grpc.ErrorCode.Builder getErrBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getErrFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.choi.service.ErrorCode err = 2;</code>
     */
    public com.choi.grpc.ErrorCodeOrBuilder getErrOrBuilder() {
      if (errBuilder_ != null) {
        return errBuilder_.getMessageOrBuilder();
      } else {
        return err_ == null ?
            com.choi.grpc.ErrorCode.getDefaultInstance() : err_;
      }
    }
    /**
     * <code>.com.choi.service.ErrorCode err = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.choi.grpc.ErrorCode, com.choi.grpc.ErrorCode.Builder, com.choi.grpc.ErrorCodeOrBuilder> 
        getErrFieldBuilder() {
      if (errBuilder_ == null) {
        errBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.choi.grpc.ErrorCode, com.choi.grpc.ErrorCode.Builder, com.choi.grpc.ErrorCodeOrBuilder>(
                getErr(),
                getParentForChildren(),
                isClean());
        err_ = null;
      }
      return errBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.choi.service.JobReply)
  }

  // @@protoc_insertion_point(class_scope:com.choi.service.JobReply)
  private static final com.choi.grpc.JobReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.choi.grpc.JobReply();
  }

  public static com.choi.grpc.JobReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JobReply>
      PARSER = new com.google.protobuf.AbstractParser<JobReply>() {
    @java.lang.Override
    public JobReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<JobReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JobReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.choi.grpc.JobReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

