// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ElasticJob.proto

package com.choi.grpc;

public interface JobRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.choi.service.JobRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nodeId = 1;</code>
   * @return The nodeId.
   */
  String getNodeId();
  /**
   * <code>string nodeId = 1;</code>
   * @return The bytes for nodeId.
   */
  com.google.protobuf.ByteString
      getNodeIdBytes();

  /**
   * <code>string resource = 2;</code>
   * @return The resource.
   */
  String getResource();
  /**
   * <code>string resource = 2;</code>
   * @return The bytes for resource.
   */
  com.google.protobuf.ByteString
      getResourceBytes();

  /**
   * <code>string parallelJobNum = 3;</code>
   * @return The parallelJobNum.
   */
  String getParallelJobNum();
  /**
   * <code>string parallelJobNum = 3;</code>
   * @return The bytes for parallelJobNum.
   */
  com.google.protobuf.ByteString
      getParallelJobNumBytes();
}
