// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ElasticJob.proto

package com.choi.grpc;

public interface JobReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.choi.service.JobReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.choi.service.GrpcJobList grpcJobList = 1;</code>
   * @return Whether the grpcJobList field is set.
   */
  boolean hasGrpcJobList();
  /**
   * <code>.com.choi.service.GrpcJobList grpcJobList = 1;</code>
   * @return The grpcJobList.
   */
  GrpcJobList getGrpcJobList();
  /**
   * <code>.com.choi.service.GrpcJobList grpcJobList = 1;</code>
   */
  GrpcJobListOrBuilder getGrpcJobListOrBuilder();

  /**
   * <code>.com.choi.service.ErrorCode err = 2;</code>
   * @return Whether the err field is set.
   */
  boolean hasErr();
  /**
   * <code>.com.choi.service.ErrorCode err = 2;</code>
   * @return The err.
   */
  ErrorCode getErr();
  /**
   * <code>.com.choi.service.ErrorCode err = 2;</code>
   */
  ErrorCodeOrBuilder getErrOrBuilder();
}
