// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ElasticJob.proto

package com.choi.grpc;

/**
 * Protobuf type {@code com.choi.service.RegisterNodeReply}
 */
public final class RegisterNodeReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.choi.service.RegisterNodeReply)
    RegisterNodeReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RegisterNodeReply.newBuilder() to construct.
  private RegisterNodeReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RegisterNodeReply() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RegisterNodeReply();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.choi.grpc.grpcService.internal_static_com_choi_service_RegisterNodeReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.choi.grpc.grpcService.internal_static_com_choi_service_RegisterNodeReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.choi.grpc.RegisterNodeReply.class, com.choi.grpc.RegisterNodeReply.Builder.class);
  }

  private int bitField0_;
  public static final int ERR_FIELD_NUMBER = 1;
  private com.choi.grpc.ErrorCode err_;
  /**
   * <code>.com.choi.service.ErrorCode err = 1;</code>
   * @return Whether the err field is set.
   */
  @java.lang.Override
  public boolean hasErr() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.com.choi.service.ErrorCode err = 1;</code>
   * @return The err.
   */
  @java.lang.Override
  public com.choi.grpc.ErrorCode getErr() {
    return err_ == null ? com.choi.grpc.ErrorCode.getDefaultInstance() : err_;
  }
  /**
   * <code>.com.choi.service.ErrorCode err = 1;</code>
   */
  @java.lang.Override
  public com.choi.grpc.ErrorCodeOrBuilder getErrOrBuilder() {
    return err_ == null ? com.choi.grpc.ErrorCode.getDefaultInstance() : err_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getErr());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getErr());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.choi.grpc.RegisterNodeReply)) {
      return super.equals(obj);
    }
    com.choi.grpc.RegisterNodeReply other = (com.choi.grpc.RegisterNodeReply) obj;

    if (hasErr() != other.hasErr()) return false;
    if (hasErr()) {
      if (!getErr()
          .equals(other.getErr())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasErr()) {
      hash = (37 * hash) + ERR_FIELD_NUMBER;
      hash = (53 * hash) + getErr().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.choi.grpc.RegisterNodeReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.choi.grpc.RegisterNodeReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.choi.grpc.RegisterNodeReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.choi.grpc.RegisterNodeReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.choi.grpc.RegisterNodeReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.choi.grpc.RegisterNodeReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.choi.grpc.RegisterNodeReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.choi.grpc.RegisterNodeReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.choi.grpc.RegisterNodeReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.choi.grpc.RegisterNodeReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.choi.grpc.RegisterNodeReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.choi.grpc.RegisterNodeReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.choi.grpc.RegisterNodeReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.choi.service.RegisterNodeReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.choi.service.RegisterNodeReply)
      com.choi.grpc.RegisterNodeReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.choi.grpc.grpcService.internal_static_com_choi_service_RegisterNodeReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.choi.grpc.grpcService.internal_static_com_choi_service_RegisterNodeReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.choi.grpc.RegisterNodeReply.class, com.choi.grpc.RegisterNodeReply.Builder.class);
    }

    // Construct using com.choi.grpc.RegisterNodeReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getErrFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      err_ = null;
      if (errBuilder_ != null) {
        errBuilder_.dispose();
        errBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.choi.grpc.grpcService.internal_static_com_choi_service_RegisterNodeReply_descriptor;
    }

    @java.lang.Override
    public com.choi.grpc.RegisterNodeReply getDefaultInstanceForType() {
      return com.choi.grpc.RegisterNodeReply.getDefaultInstance();
    }

    @java.lang.Override
    public com.choi.grpc.RegisterNodeReply build() {
      com.choi.grpc.RegisterNodeReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.choi.grpc.RegisterNodeReply buildPartial() {
      com.choi.grpc.RegisterNodeReply result = new com.choi.grpc.RegisterNodeReply(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.choi.grpc.RegisterNodeReply result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.err_ = errBuilder_ == null
            ? err_
            : errBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.choi.grpc.RegisterNodeReply) {
        return mergeFrom((com.choi.grpc.RegisterNodeReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.choi.grpc.RegisterNodeReply other) {
      if (other == com.choi.grpc.RegisterNodeReply.getDefaultInstance()) return this;
      if (other.hasErr()) {
        mergeErr(other.getErr());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getErrFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.choi.grpc.ErrorCode err_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.choi.grpc.ErrorCode, com.choi.grpc.ErrorCode.Builder, com.choi.grpc.ErrorCodeOrBuilder> errBuilder_;
    /**
     * <code>.com.choi.service.ErrorCode err = 1;</code>
     * @return Whether the err field is set.
     */
    public boolean hasErr() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.com.choi.service.ErrorCode err = 1;</code>
     * @return The err.
     */
    public com.choi.grpc.ErrorCode getErr() {
      if (errBuilder_ == null) {
        return err_ == null ? com.choi.grpc.ErrorCode.getDefaultInstance() : err_;
      } else {
        return errBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.choi.service.ErrorCode err = 1;</code>
     */
    public Builder setErr(com.choi.grpc.ErrorCode value) {
      if (errBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        err_ = value;
      } else {
        errBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.choi.service.ErrorCode err = 1;</code>
     */
    public Builder setErr(
        com.choi.grpc.ErrorCode.Builder builderForValue) {
      if (errBuilder_ == null) {
        err_ = builderForValue.build();
      } else {
        errBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.com.choi.service.ErrorCode err = 1;</code>
     */
    public Builder mergeErr(com.choi.grpc.ErrorCode value) {
      if (errBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          err_ != null &&
          err_ != com.choi.grpc.ErrorCode.getDefaultInstance()) {
          getErrBuilder().mergeFrom(value);
        } else {
          err_ = value;
        }
      } else {
        errBuilder_.mergeFrom(value);
      }
      if (err_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.com.choi.service.ErrorCode err = 1;</code>
     */
    public Builder clearErr() {
      bitField0_ = (bitField0_ & ~0x00000001);
      err_ = null;
      if (errBuilder_ != null) {
        errBuilder_.dispose();
        errBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.com.choi.service.ErrorCode err = 1;</code>
     */
    public com.choi.grpc.ErrorCode.Builder getErrBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getErrFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.choi.service.ErrorCode err = 1;</code>
     */
    public com.choi.grpc.ErrorCodeOrBuilder getErrOrBuilder() {
      if (errBuilder_ != null) {
        return errBuilder_.getMessageOrBuilder();
      } else {
        return err_ == null ?
            com.choi.grpc.ErrorCode.getDefaultInstance() : err_;
      }
    }
    /**
     * <code>.com.choi.service.ErrorCode err = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.choi.grpc.ErrorCode, com.choi.grpc.ErrorCode.Builder, com.choi.grpc.ErrorCodeOrBuilder> 
        getErrFieldBuilder() {
      if (errBuilder_ == null) {
        errBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.choi.grpc.ErrorCode, com.choi.grpc.ErrorCode.Builder, com.choi.grpc.ErrorCodeOrBuilder>(
                getErr(),
                getParentForChildren(),
                isClean());
        err_ = null;
      }
      return errBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.choi.service.RegisterNodeReply)
  }

  // @@protoc_insertion_point(class_scope:com.choi.service.RegisterNodeReply)
  private static final com.choi.grpc.RegisterNodeReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.choi.grpc.RegisterNodeReply();
  }

  public static com.choi.grpc.RegisterNodeReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RegisterNodeReply>
      PARSER = new com.google.protobuf.AbstractParser<RegisterNodeReply>() {
    @java.lang.Override
    public RegisterNodeReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RegisterNodeReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RegisterNodeReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.choi.grpc.RegisterNodeReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

