// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ElasticJob.proto

package com.choi.grpc;

public interface RegisterNodeReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.choi.service.RegisterNodeReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.choi.service.ErrorCode err = 1;</code>
   * @return Whether the err field is set.
   */
  boolean hasErr();
  /**
   * <code>.com.choi.service.ErrorCode err = 1;</code>
   * @return The err.
   */
  ErrorCode getErr();
  /**
   * <code>.com.choi.service.ErrorCode err = 1;</code>
   */
  ErrorCodeOrBuilder getErrOrBuilder();
}
