server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myDatabase?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  redis:
    timeout: 10000
    cluster:
      nodes: 192.168.17.128:7001, 192.168.17.128:7002, 192.168.17.128:7003, 192.168.17.128:7004, 192.168.17.128:7005, 192.168.17.128:7006
    jedis:
      pool:
        max-active: 8
        max-idle: 4
        min-idle: 0
        max-wait: -1

#mybatis:
#  type-aliases-package: com.choi.pojo
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
